# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='business',
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
