# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20190531_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
