# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-01 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='location',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='hood.Neighbourhood'),
            preserve_default=False,
        ),
    ]
